<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Quiz;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class QuizSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        Quiz::insert([
            [
                'category_id' => 1,
                'question' => 'Kamu melihat seorang teman diejek terus-menerus di grup chat kelas. Apa yang sebaiknya kamu lakukan?',
                'option_a' => 'Ikut tertawa agar tidak dianggap lemah oleh teman-teman',
                'option_b' => 'Diam saja karena takut jadi target berikutnya',
                'option_c' => 'Melaporkan ke guru atau wali kelas agar ditindaklanjuti',
                'option_d' => 'Membalas ejekan dengan ejekan lain untuk membela temanmu',
                'correct_answer' => 'C',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'question' => 'Seorang influencer di media sosial membagikan tren diet ekstrem untuk menurunkan berat badan dalam waktu singkat. Bagaimana seharusnya kamu merespons?',
                'option_a' => 'Mencobanya karena ingin cepat langsing',
                'option_b' => 'Membagikan ulang ke teman-teman agar mereka juga mencobanya',
                'option_c' => 'Mencari informasi dari sumber terpercaya sebelum mengikuti tren',
                'option_d' => 'Mengomentari postingannya dengan ejekan',
                'correct_answer' => 'C',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'question' => 'Temanmu memaksamu untuk mencoba merokok agar diterima dalam geng mereka. Apa yang kamu lakukan?',
                'option_a' => 'Mencoba sekali saja agar tidak dianggap pengecut',
                'option_b' => 'Menolak dan menjauhi lingkungan yang memberi pengaruh buruk',
                'option_c' => 'Menantang balik mereka dengan mengajak ke kegiatan lain',
                'option_d' => 'Mengikuti permintaan mereka tapi dengan ragu-ragu',
                'correct_answer' => 'B',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'question' => 'Di media sosial, ada tantangan berbahaya yang viral, seperti "blackout challenge" yang meminta orang menahan napas sampai pingsan. Apa tindakan terbaik?',
                'option_a' => 'Mengingatkan teman-teman tentang bahayanya',
                'option_b' => 'Mencobanya agar tidak ketinggalan tren',
                'option_c' => 'Merekam seseorang yang mencobanya dan mempostingnya',
                'option_d' => 'Mengabaikannya karena bukan urusanmu',
                'correct_answer' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'question' => 'Kamu baru saja melihat seorang teman dipukul oleh senior di sekolah. Apa langkah terbaik yang bisa kamu ambil?',
                'option_a' => 'Melaporkan kejadian itu ke guru atau pihak sekolah',
                'option_b' => 'Membalas dengan kekerasan agar tidak diremehkan',
                'option_c' => 'Merekam dan menyebarkan videonya untuk mendapat perhatian',
                'option_d' => 'Diam saja karena takut ikut terlibat',
                'correct_answer' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // category 2
            [
                'category_id' => 2,
                'question' => 'Kamu melihat temanmu sering bolos sekolah untuk bermain game di warnet. Dia meminta kamu untuk ikut bolos karena menurutnya sekolah itu membosankan. Apa yang kamu lakukan?',
                'option_a' => 'Menolaknya dan mengajaknya bicara tentang dampak bolos sekolah',
                'option_b' => 'Ikut sekali saja, toh guru tidak akan tahu',
                'option_c' => 'Menyarankan bolos di hari yang tidak ada ujian atau tugas penting',
                'option_d' => 'Melaporkan ke guru tanpa memberi tahu temanmu terlebih dahulu',
                'correct_answer' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'question' => 'Temanmu ketahuan menyontek saat ujian dan meminta kamu untuk membelanya jika guru menuduhnya. Apa tindakan terbaik?',
                'option_a' => 'Membelanya agar persahabatan kalian tetap baik',
                'option_b' => 'Menyarankan dia untuk mengakui kesalahannya dan menerima konsekuensinya',
                'option_c' => 'Menghindar agar tidak terlibat dalam masalah ini',
                'option_d' => 'Ikut menyontek lain kali agar nilaimu juga bagus',
                'correct_answer' => 'B',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'question' => 'Seseorang menyebarkan gosip buruk tentangmu di sekolah. Bagaimana cara terbaik untuk menangani situasi ini?',
                'option_a' => 'Menghadapinya dengan tenang dan mencari tahu siapa penyebarnya',
                'option_b' => 'Membalas dengan menyebarkan gosip tentang orang tersebut',
                'option_c' => 'Berkelahi dengannya agar semua orang tahu kamu tidak takut',
                'option_d' => 'Mengunci diri di kamar dan menghindari sekolah',
                'correct_answer' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'question' => 'Saat jalan pulang sekolah, kamu melihat temanmu mengambil barang milik orang lain tanpa izin. Apa yang harus kamu lakukan?',
                'option_a' => 'Berpura-pura tidak melihat agar tidak ikut campur',
                'option_b' => 'Langsung melaporkannya ke guru tanpa memberinya kesempatan untuk menjelaskan',
                'option_c' => 'Menasihatinya agar mengembalikan barang tersebut dan menjelaskan akibatnya',
                'option_d' => 'Ikut mengambil barang lain agar tidak dianggap pengecut',
                'correct_answer' => 'C',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'question' => 'Kamu mendapat tawaran untuk bergabung dalam geng yang terkenal sering melakukan tawuran. Mereka bilang kamu akan lebih dihormati jika bergabung. Apa yang harus kamu lakukan?',
                'option_a' => 'Menolak dan mencari lingkungan pertemanan yang lebih positif',
                'option_b' => 'Bergabung karena takut dianggap pengecut',
                'option_c' => 'Bergabung tapi hanya sebagai "pengamat" agar tidak kena masalah',
                'option_d' => 'Menantang mereka dengan kelompok lain untuk membuktikan kekuatanmu',
                'correct_answer' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // category 3
            [
                'category_id' => 3,
                'question' => 'Temanmu sering merendahkanmu di depan orang lain dan menganggapnya hanya sebagai "candaan." Bagaimana reaksi terbaik?',
                'option_a' => 'Memintanya berhenti dan menjelaskan bahwa kamu tidak nyaman',
                'option_b' => 'Membiarkannya karena takut kehilangan teman',
                'option_c' => 'Membalas dengan ejekan yang lebih keras',
                'option_d' => 'Menghindarinya tanpa memberi tahu alasan',
                'correct_answer' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'question' => 'Pacarmu selalu meminta kata sandi media sosialmu dan marah jika kamu tidak memberikannya. Ini adalah tanda…',
                'option_a' => 'Kepedulian',
                'option_b' => 'Rasa cinta yang dalam',
                'option_c' => 'Hubungan yang tidak sehat',
                'option_d' => 'Sikap yang wajar dalam pacaran',
                'correct_answer' => 'C',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'question' => 'Seorang temanmu selalu memanfaatkanmu untuk meminjam uang, tetapi jarang membayar kembali. Apa yang harus kamu lakukan?',
                'option_a' => 'Menegurnya dengan sopan dan menetapkan batasan',
                'option_b' => 'Tetap meminjaminya karena dia teman baikmu',
                'option_c' => 'Menagih dengan cara kasar agar dia takut',
                'option_d' => 'Menghindarinya tanpa membicarakan masalah ini',
                'correct_answer' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'question' => 'Bagaimana ciri-ciri hubungan pertemanan yang sehat?',
                'option_a' => 'Saling menghormati dan mendukung satu sama lain',
                'option_b' => 'Saling mengejek dan menjatuhkan demi "candaan"',
                'option_c' => 'Harus selalu bersama setiap saat',
                'option_d' => 'Hanya peduli jika membutuhkan bantuan',
                'correct_answer' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'question' => 'Temanmu sering mengancam akan menyakiti diri sendiri jika kamu tidak menuruti keinginannya. Apa langkah terbaik?',
                'option_a' => 'Mengajak berbicara dengan baik dan menyarankan mencari bantuan profesional',
                'option_b' => 'Menuruti keinginannya agar dia tidak melakukan hal buruk',
                'option_c' => 'Mengabaikannya karena itu bukan urusanmu',
                'option_d' => 'Mengancam balik dengan cara yang sama',
                'correct_answer' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // kategori 4
            [
                'category_id' => 4,
                'question' => 'Kamu mendapat pesan dari seseorang yang mengaku sebagai panitia lomba dan meminta data pribadimu. Apa langkah terbaik?',
                'option_a' => 'Memberikan data yang diminta agar tidak ketinggalan lomba',
                'option_b' => 'Mengecek sumber resmi sebelum memberikan informasi pribadi',
                'option_c' => 'Mengabaikannya karena tidak peduli',
                'option_d' => 'Mengirimkan data asal-asalan agar mereka bingung',
                'correct_answer' => 'B',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 4,
                'question' => 'Bagaimana cara mengenali berita hoaks di media sosial?',
                'option_a' => 'Jika sudah banyak yang membagikan, berarti itu benar',
                'option_b' => 'Cek sumber berita dan lakukan verifikasi dari sumber terpercaya',
                'option_c' => 'Percaya saja karena tampilannya terlihat meyakinkan',
                'option_d' => 'Jika berita itu sesuai dengan pendapatmu, pasti benar',
                'correct_answer' => 'B',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 4,
                'question' => 'Apa yang sebaiknya dilakukan jika kamu mengalami cyberbullying di media sosial?',
                'option_a' => 'Melaporkan dan memblokir pelaku',
                'option_b' => 'Membalas dengan komentar yang lebih kasar',
                'option_c' => 'Menghapus akun media sosial dan menghilang',
                'option_d' => 'Mengabaikannya karena tidak bisa dihentikan',
                'correct_answer' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 4,
                'question' => 'Seorang teman mengunggah foto yang mempermalukanmu tanpa izin. Apa yang harus kamu lakukan?',
                'option_a' => 'Memintanya menghapus foto dengan sopan',
                'option_b' => 'Membalas dengan mengunggah foto buruknya',
                'option_c' => 'Menyebarkannya ke lebih banyak orang agar dia mendapat pelajaran',
                'option_d' => 'Tidak peduli selama tidak terlalu mempermalukanmu',
                'correct_answer' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 4,
                'question' => 'Apa tindakan terbaik untuk menjaga privasi online?',
                'option_a' => 'Menggunakan kata sandi yang kuat dan tidak membagikannya kepada siapa pun',
                'option_b' => 'Menggunakan satu kata sandi yang sama untuk semua akun agar mudah diingat',
                'option_c' => 'Menerima semua permintaan pertemanan agar lebih banyak followers',
                'option_d' => 'Mengunggah informasi pribadi seperti alamat dan nomor telepon agar lebih mudah dihubungi',
                'correct_answer' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
